Tags on facility form
Green-Kittens/bathroom-finder-frontend pull request #111
Opened 2024-05-08 09:36 UTC by k4yluh

Adding tags UI on facility form

2024-05-10 17:37 UTC, dylantompkins commented
Kayla has requested that we all review this PR

2024-05-10 17:54 UTC, dylantompkins requested changes
Note: have not looked at the code yet

2024-05-10 17:54 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
Title text "Add a new facility" is cut off by the top bar

2024-05-10 17:54 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
I think you made the map bigger. Was that intended?

2024-05-10 17:54 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
The way you implemented visually showing which items are enabled and disabled is not obvious to the user. Even if I do notice that the text is a different color, I don't know which color means "yes" and which color means "no". Here's two options that I think are more obvious:

1. Make this a checklist instead of a collection of bubbles. Checkboxes are easy to see what is on or off, and most users will recognize them.
2. Instead of toggling the visual style of the button, toggle the text that the button displays. For instance "Wheelchair Accessible" and "Not Wheelcahir Accessible"

2024-05-17 17:27 UTC, k4yluh commented on navigation/screens/facility-form.tsx
I didn't?

2024-05-17 19:14 UTC, meganfung38 submitted a review, later dismissed
looks good

2024-05-17 20:44 UTC, dylantompkins requested changes
Note: have not looked at code yet

2024-05-17 20:44 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
Submit facility button is now cut off at the bottom

2024-05-20 19:28 UTC, dylantompkins requested changes

2024-05-20 19:28 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
> +                      color: tags.wheelchairAccessible ? "#007AFF" : "#6da798",
reused color values should be bound to a constant, not magic number

2024-05-20 19:28 UTC, dylantompkins commented on navigation/screens/facility-form.tsx
> +    borderColor: "#6da798",
reused color value should be a constant, not magic number

2024-05-22 19:54 UTC, dylantompkins approved these changes

2024-05-22 19:56 UTC, meganfung38 approved these changes
looks good

2024-05-22 20:04 UTC, JonasSchiessl approved these changes
Looks, good i can see the other bathrooms

2024-05-22 20:51 UTC, lindlands requested changes
The tag system is a bit confusing. I think it would be better it the tags were didn't have the "not"--by not selecting a tag, does that mean it defaults to the "not"?
I expected that, on selection, the tag would change to the selected colors and the text would stay the same (i.e. I select "Not Wheelchair Accessible" to tag the bathroom as such)

2024-05-24 19:36 UTC, kaylantran commented
To resolve @lindlands point, there will be a follow up issue and/or review spike

2024-05-24 19:41 UTC, merged