updated controllers
Green-Kittens/bathroom-finder-frontend pull request #126
Opened 2024-05-15 19:31 UTC by JonasSchiessl

Changed the types to capital, removed unnecessary login, register, forgot password controller functions.

2024-05-15 19:40 UTC, meganfung38 approved these changes
looks good

2024-05-15 19:53 UTC, meganfung38 requested changes

2024-05-15 19:53 UTC, meganfung38 commented on types/facility.ts
[{"Category": "Womens", "Coordinates": [], "Date": "2024-03-02T00:00:00.000Z", "Favorites": 1, "Name": "Restroom1", "Operations": "8am-9pm", "PictureURL": ["https://example.com/index.html"], "RatingAVG": 4.5, "Reports": 0, "Reviews": ["65e3cc149aa3eada64c4c739"], "Tags": ["Clean", "Feminine Products"], "_id": "65e3c7599aa3eada64c4c737", "coordinates": [64, 72]}]

this is what the controller function returns-- why is there a "Coordinates" and "coordinates", one should be deleted.

2024-05-15 19:53 UTC, meganfung38 commented on types/facility.ts
Also, how would I access the facility id if it isn't defined here in the type. I need the facility id to call the reviewController function.

2024-05-17 03:45 UTC, meganfung38 approved these changes
Looks good

2024-05-17 06:33 UTC, JonasSchiessl commented
Can everyone review this one please.

2024-05-17 09:57 UTC, k4yluh submitted a review, later dismissed
Looks good!

2024-05-17 19:27 UTC, lindlands submitted a review, later dismissed
Looks good!

2024-05-17 19:32 UTC, dylantompkins commented
```
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@8.0.0 - expected version: 8.0.1
  expo@51.0.5 - expected version: ~51.0.8
  expo-image-picker@15.0.4 - expected version: ~15.0.5
  jest-expo@51.0.1 - expected version: ~51.0.2
Your project may not work correctly until you install the expected versions of the packages.
```

2024-05-17 20:00 UTC, dylantompkins approved these changes
thank you for updating packages. LGTM

2024-05-17 20:01 UTC, merged