Issue #44- Adding navigation
Green-Kittens/bathroom-finder-frontend pull request #3
Opened 2024-03-04 19:38 UTC by meganfung38

- created navbar with navigation to review form, main (home page with map view), and user profile screens 
- implemented navigation through buttons on screens: 
1. press map on main screen --> navigates to facility profiles screen
2. press see more on facilities profiles screen --> navigates to facility reviews screen 
3. press submit on review form screen --> navigates to main screen 
4. press logout on user profile screen --> navigates to login screen 
5. press login on login screen --> navigates to main screen

2024-03-15 21:58 UTC, dylantompkins requested changes
Please make the follow-up issue for the login route and remove the Alert.

Other than that, looks really good!

2024-03-15 21:58 UTC, dylantompkins commented on navigation/navbar.tsx
> +      initialRouteName={mainName} // ask about implementing login as initial page display
Note: login doesn't *have* to be the initial page. for instance, someone can look at the map without logging in. we only need to log in if someone wants to write data

2024-03-15 21:58 UTC, dylantompkins commented on navigation/screens/login.tsx
>      Alert.alert("Login Pressed", "Navigate to home screen.");
remove this alert
```suggestion
```

2024-03-15 21:58 UTC, dylantompkins commented on navigation/screens/login.tsx
Currently there is no way to get to this page. We need to either:
- make it the default page and force everyone to always be logged in
- check if someone is logged in right before they need to be logged in for something and redirect them here

Megan: please make an issue to do this in the future. This comment is not blocking merge

2024-03-15 21:58 UTC, dylantompkins commented on yarn.lock
did not know that we were using yarn for this repo. make sure other people know that since we've been using npm for everything else so far

2024-03-16 17:46 UTC, meganfung38 commented
Cool just completed all the requested changes and made an issue for the login navigation.

2024-03-18 05:24 UTC, dylantompkins requested changes
thanks for deleting alert, but it looks like your branch now has merge conflicts. to resolve:
1. check out your branch
2. merge main into your branch
3. resolve any merge conflicts with additional commits on your branch

when you are done, please re-request my review

2024-03-18 15:13 UTC, meganfung38 commented
Just resolved the merge conflict!

2024-04-08 19:47 UTC, closed without merging