Issue #39: Add image picker
Green-Kittens/bathroom-finder-frontend pull request #53
Opened 2024-04-13 23:27 UTC by meganfung38

Issue #39 : 
- image picker available on facility-form screen,  review-form screen, and user-profile screen
NOTE: Image picker needs implementation on register screen-- screen needs to be created

2024-04-14 01:08 UTC, JonasSchiessl commented
You have some merge conflicts in package.json.

2024-04-14 20:51 UTC, dylantompkins commented
![image](https://github.com/Green-Kittens/bathroom-finder-frontend/assets/36244177/c0bffde4-bbd4-42e6-9713-0f8a86977119)

Cannot review photos on iOS, the names don't show just the trashcan

2024-04-14 20:55 UTC, dylantompkins commented
super impressed with the profile picture stuff. seems to be all working. might be time to change the default profile picture from the goat to something generic

2024-04-14 20:57 UTC, dylantompkins commented
Please update package.json accordingly:
```
The following packages should be updated for best compatibility with the installed expo version:
  @react-native-community/datetimepicker@7.6.4 - expected version: 7.6.1
  react-native-gesture-handler@2.16.0 - expected version: ~2.14.0
Your project may not work correctly until you install the correct versions of the packages.
```

2024-04-15 01:13 UTC, JonasSchiessl requested changes
Looks good, just some comments and things that need to be changed in the package.  Also, make sure you pull the latest changes from main.

2024-04-15 01:13 UTC, JonasSchiessl commented on navigation/navbar.tsx
I thought we would have a single plus button that would then expand to give the options of add review or add facility.

2024-04-15 01:13 UTC, JonasSchiessl commented on package.json
please fix the packages 
<img width="767" alt="Screenshot 2024-04-14 at 6 06 02 PM" src="https://github.com/Green-Kittens/bathroom-finder-frontend/assets/64995252/bfa76e7b-f609-499f-9609-2401a0dd93a6">

2024-04-15 01:13 UTC, JonasSchiessl commented on navigation/screens/user-profile.tsx
IOS has no preview, are there supposed to be image previews of the ones you uploaded?

2024-04-15 02:21 UTC, meganfung38 commented on navigation/navbar.tsx
Yeah that is the plan but I just put the facility-form in the navbar for now (so that the screen can be reviewed) because the plus sign that would expand to give those options has not been implemented by the person it was assigned to.

2024-04-15 02:22 UTC, meganfung38 commented on navigation/screens/user-profile.tsx
if you click on the image links a modal should pop up with the image uploaded.

2024-04-15 02:30 UTC, meganfung38 commented on navigation/screens/user-profile.tsx
what do you mean image preview? For the facility-form and review-form screens if you click on the image links, a modal should pop up with the uploaded image. For the user-profile screen, you should be able to click on the profile picture to upload, change, or remove your profile picture

2024-04-15 02:44 UTC, JonasSchiessl approved these changes
Good Job Megan! 🥳

2024-04-15 02:44 UTC, merged