Issue #66: Add coordinates
Green-Kittens/bathroom-finder-frontend pull request #89
Opened 2024-04-26 20:39 UTC by meganfung38

Issue #66 :  
- assigns a location to newly created facilities on facility-form screen 

What to expect:
- map view of user's current location and pin marker (represents location that will be assigned to the newly created facility) 
- drag pin marker to relocate location of facility 
- press pin marker to see its address in a modal 
       - if location of pin marker is a building, address will be name of building 
       - if not, address will be the pin marker 

**NOTE: using mapView callout component did not work out-- cannot figure out how to make address fit inside callout (no style container to fix issue)

2024-04-28 01:13 UTC, dylantompkins requested changes
After initial testing on phone, a few things:
1. It's hard to pinch to zoom on the map because it's small. I think doubling the height would be reasonable.
2. The default zoom of the map is pretty zoomed out. Maybe making the map bigger will zoom it in. If not, default zoom should be increased IMO.
3. The time displays now show seconds. I don't think they did before. Also, the selector doesn't allow you to choose the seconds. It should probably just go back to minutes.
4. The scroll view does not allow you to scroll all the way down.

2024-04-28 01:16 UTC, dylantompkins commented
![image](https://github.com/Green-Kittens/bathroom-finder-frontend/assets/36244177/ae5d824a-8faa-4f31-ad02-3785492c66b7)
- Scrolled all the way down (see scroll bar on the right)
- Time bubbles show seconds

![image](https://github.com/Green-Kittens/bathroom-finder-frontend/assets/36244177/10c7c3aa-0851-4018-b859-ded0cda1ac6d)
- Time selector does not allow seconds, creating a UX discrepancy

2024-05-01 20:18 UTC, meganfung38 commented
What to expect (after PR requested changes): 
- map view of user's current location and pin marker (represents location that will be assigned to the newly created facility)
- map view should be zoomed enough to see nearby buildings
- map view height should be a reasonable height for map maneuvering
- scroll view should work
- drag pin marker to relocate location of facility
- press pin marker to see its address in a modal
- if location of pin marker is a building, address will be name of building
- if not, address will be the pin marker
- time selector should not show seconds (format: HH: MM)

2024-05-01 21:00 UTC, lindlands requested changes

2024-05-01 21:00 UTC, lindlands commented on navigation/screens/facility-form.tsx
> +          <Text>press and drag pin marker to see address and relocate</Text>
Nit: capitalize Press

2024-05-01 21:00 UTC, lindlands commented on navigation/screens/facility-form.tsx
> +  scrollView: {
There is a lot of scroll left at the bottom of the page with no content. Can this be fixed?

2024-05-02 01:25 UTC, dylantompkins approved these changes
Looks great!!

2024-05-02 01:37 UTC, lindlands approved these changes
Nice job!!

2024-05-02 01:37 UTC, merged